// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgjlUkEWG0ic1fxT4iIpEvV8rJyr5EKQY',
    appId: '1:405166012261:web:e9702eba33e786d707938c',
    messagingSenderId: '405166012261',
    projectId: 'daleel-al-motafawqeen',
    authDomain: 'daleel-al-motafawqeen.firebaseapp.com',
    storageBucket: 'daleel-al-motafawqeen.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhy5HdmojgdpedBECCBmWg6pXEq-cwRKc',
    appId: '1:405166012261:android:1730ee1dda41075d07938c',
    messagingSenderId: '405166012261',
    projectId: 'daleel-al-motafawqeen',
    storageBucket: 'daleel-al-motafawqeen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA88uMYebdXEpRaODp9h3HxeoV67PKP7w8',
    appId: '1:405166012261:ios:16980335314473ad07938c',
    messagingSenderId: '405166012261',
    projectId: 'daleel-al-motafawqeen',
    storageBucket: 'daleel-al-motafawqeen.firebasestorage.app',
    iosBundleId: 'com.example.daleelAlMotafawqeen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA88uMYebdXEpRaODp9h3HxeoV67PKP7w8',
    appId: '1:405166012261:ios:16980335314473ad07938c',
    messagingSenderId: '405166012261',
    projectId: 'daleel-al-motafawqeen',
    storageBucket: 'daleel-al-motafawqeen.firebasestorage.app',
    iosBundleId: 'com.example.daleelAlMotafawqeen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgjlUkEWG0ic1fxT4iIpEvV8rJyr5EKQY',
    appId: '1:405166012261:web:f50863a3d3c9bac907938c',
    messagingSenderId: '405166012261',
    projectId: 'daleel-al-motafawqeen',
    authDomain: 'daleel-al-motafawqeen.firebaseapp.com',
    storageBucket: 'daleel-al-motafawqeen.firebasestorage.app',
  );
}
